### ISSUE TITLE
Hi fongyk

### ISSUE THREAD

**Issue by willard-yuan** [fongyk/ClothesRetrievalTools#1]
Hi fongyk，我在寻找在图像、视频检索领域做得比较专、比较深的人，我的个人介绍见[这里](http://yongyuan.name/cn/)，不知是否能加个微信？谢谢！

**Comment by fongyk** [comment]
您好，我已经把微信发到了您的gmail邮箱，请注意查收。

**Comment by fongyk** [comment]
> Hi fongyk，我在寻找在图像、视频检索领域做得比较专、比较深的人，我的个人介绍见[这里](http://yongyuan.name/cn/)，不知是否能加个微信？谢谢！

您好，我已经把微信发到了您的gmail邮箱，请注意查收。
